### ISSUE TITLE
实战的过程中对方上线了却还是获取不到key。

### ISSUE THREAD

**Issue by cdxiaodong** [AdminTest0/SharpWxDump#1]
提一个issue  我本地测本地cs上线是可以的  但是在实战的过程中对方上线了并且截图发现打开wx了
却还是获取不到key。无论是system还是admin用户。问一下大佬还有什么限制存在吗

**Comment by AdminTest0** [comment]
> 提一个issue 我本地测本地cs上线是可以的 但是在实战的过程中对方上线了并且截图发现打开wx了 却还是获取不到key。无论是system还是admin用户。问一下大佬还有什么限制存在吗

报的什么错误

**Comment by cdxiaodong** [comment]
![QQ截图20220722104701](https://user-images.githubusercontent.com/84082748/180351875-ba2a2330-40bb-42f6-969e-73e5498c48e2.jpg)

**Comment by AdminTest0** [comment]
> ![QQ截图20220722104701](https://user-images.githubusercontent.com/84082748/180351875-ba2a2330-40bb-42f6-969e-73e5498c48e2.jpg)

已修复

**Comment by shuaxingzi** [comment]
8.26号更新后编译的exe文件，报的和上面一样的错误
![image](https://user-images.githubusercontent.com/44746140/187114552-cabde20e-253e-4a04-9cba-bdd5d0606dda.png)

**Comment by shmilylty** [comment]
@shuaxingzi 编译命令`C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe .\Program.cs  /platform:x86`，再试一下。

**Comment by shuaxingzi** [comment]
> @shuaxingzi 编译命令`C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe .\Program.cs /platform:x86`，再试一下。

编译成功，可以正常使用，感谢师傅

**Comment by cqkenuo** [comment]
3.7.6.44好像不能使用
