### ISSUE TITLE
大佬您好想请教一下

### ISSUE THREAD

**Issue by FCB-Barcelona** [AdminTest0/SharpWxDump#10]
为什么我登陆了微信还是显示WeChat Base Address Get Faild呢
![679b9dcbb26e95975ff11c6f8bef0dc](https://user-images.githubusercontent.com/61531856/201662314-de1c5fa2-c368-4fc6-8f4f-ccf842687788.png)

**Comment by AdminTest0** [comment]
因为要编译成x86的

**Comment by AdminTest0** [comment]
给个联系方式 我编译好发你

**Comment by FCB-Barcelona** [comment]
qq:2061673940


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AdminTest0/SharpWxDump"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AdminTest0/SharpWxDump] 大佬您好想请教一下 (Issue #10)





 
给个联系方式 我编译好发你

**Comment by FCB-Barcelona** [comment]
qq:2061673940，麻烦大佬了

**Comment by FCB-Barcelona** [comment]
收到了，可以运行，可能是我这边编译出了问题？谢谢大佬的帮忙

**Comment by AdminTest0** [comment]
我用的是VSCode 2019、新建项目：控制台应用(.NET Framework)、目标框架：.NET Framework 4、平台：Release x86

**Comment by FCB-Barcelona** [comment]
我是在Microsoft.NET目录底下framework和framework里面编译的

**Comment by FCB-Barcelona** [comment]
我是在Microsoft.NET目录底下framework和framework64里面编译的

**Comment by AdminTest0** [comment]
那估计少了什么东西，用vs2019没问题，上面打错了，是Visual Studio 2019

**Comment by FCB-Barcelona** [comment]
大佬请问一下，为什么我换了一台电脑就不可以正常是用了，没有报错但是显示微信没有运行，是因为缺少库吗
![3d9171fed13d5f7e637278988b858c9](https://user-images.githubusercontent.com/61531856/201676866-6cbb3c08-ce51-4078-a265-1b424acccbdf.jpg)

**Comment by AdminTest0** [comment]
这个没碰到过，你可以试试重新登录一下微信，然后再运行，一般不会报这个错误，或者你使用的微信是官方版本的吗
