### ISSUE TITLE
调试输出微信 process 模组找不到 名为 WeChatWin.dll 的

### ISSUE THREAD

**Issue by Bian-Sh** [AdminTest0/SharpWxDump#17]
![image](https://user-images.githubusercontent.com/24520547/211967658-385c2473-420e-4de0-ae21-e7ae211f6a30.png)
系统： window 10
微信版本：3.8.1.26

**Comment by chaohui2** [comment]
vs的平台改成x86就可以了。
![image](https://user-images.githubusercontent.com/17821872/215052029-d9a9a477-bff2-4cbc-bf3b-12d6d3235f08.png)
