### ISSUE TITLE
能否在release提供打包好的程序？（正文中提供一个23.4.2打包好的）

### ISSUE THREAD

**Issue by yxzlwz** [AdminTest0/SharpWxDump#23]
现在这个操作起来还是比较麻烦（甚至自己为此安装了vs），能否在release中提供打包好的程序？

此处提供一个23.4.2打包好的程序，供同道中人使用

[Program.zip](https://github.com/AdminTest0/SharpWxDump/files/11131259/Program.zip)

**Comment by AdminTest0** [comment]
项目开源，不考虑编译打包文件，容易误会，vs2019直接编译就好了
