### ISSUE TITLE
内存基址如何获取

### ISSUE THREAD

**Issue by admin-ping** [AdminTest0/SharpWxDump#29]
授人以鱼不如授人以渔，建议作者可以详细讲讲如何获取版本对应list里的内存基址（最好是cheat engine的教程）

**Comment by AdminTest0** [comment]
已采纳，https://github.com/AdminTest0/SharpWxDump/blob/master/CE%E8%8E%B7%E5%8F%96%E5%9F%BA%E5%9D%80.md

**Comment by 774649283** [comment]
请问下这个000024是怎么得来的，新版本3.9.6系列的用用户名-000024得到的值好像不是key的值了，3.9.2系列测试还是对的
![image](https://github.com/AdminTest0/SharpWxDump/assets/17950491/2f566471-e52a-4aeb-9363-ff021cde35d4)
