### ISSUE TITLE
解密脚本不行,说密码错误

### ISSUE THREAD

**Issue by leehom66** [AdminTest0/SharpWxDump#3]
![微信截图_20220729031823](https://user-images.githubusercontent.com/104624034/181619958-bf38bdb4-2a4a-48d9-80aa-c100e7a0c79a.png)
WeChatVersion: 3.7.5.23

**Comment by AdminTest0** [comment]
> ![微信截图_20220729031823](https://user-images.githubusercontent.com/104624034/181619958-bf38bdb4-2a4a-48d9-80aa-c100e7a0c79a.png) WeChatVersion: 3.7.5.23

如果本机登录过多个微信，WeChat Files文件夹下会有多个目录，有没有可能是MSG0.db文件复制错了
这边又测了一遍，没有问题

![image](https://user-images.githubusercontent.com/33925462/181667756-6050d677-5415-49fa-a2f8-e134daff42d2.png)
