### ISSUE TITLE
(int)Program.WeChatWinBaseAddress int不适合基地址

### ISSUE THREAD

**Issue by Jeck-Liu-Create** [AdminTest0/SharpWxDump#38]
微信版本：3.9.5.73
程序获取到的WeChatWinBaseAddress  = 0x00007ff8a1c80000，直接报错退出了

**Comment by DBG-QT** [comment]
更新的这个版本是64位了
能发一份这个版本吗

**Comment by DBG-QT** [comment]
> > 更新的这个版本是64位了 能发一份这个版本吗
> 
> 还有一个帖子说这个问题，我的也不行

我是说微信的版本能发一个给我吗

**Comment by Jeck-Liu-Create** [comment]
这个微信版本：3.9.5.73吗？

**Comment by DBG-QT** [comment]
> 这个微信版本：3.9.5.73吗？

嗯

**Comment by DBG-QT** [comment]
kuhucinoto@outlook.com

**Comment by djhai** [comment]
请问下这版本的sqlite key 基址怎么查？

**Comment by Jeck-Liu-Create** [comment]
>新版的这个方法已经无效了

**Comment by DBG-QT** [comment]
已经有人搞定了
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Liu ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月8日 17:40
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [AdminTest0/SharpWxDump] (int)Program.WeChatWinBaseAddress int不适合基地址 (Issue #38)
        
      
    
  


新版的这个方法已经无效了

**Comment by Jeck-Liu-Create** [comment]
> 已经有人搞定了 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 Liu ***@***.***> 发送日期 2023年6月8日 17:40 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [AdminTest0/SharpWxDump] (int)Program.WeChatWinBaseAddress int不适合基地址 (Issue #38) 新版的这个方法已经无效了 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

不太清楚
