### ISSUE TITLE
攻防练习中是把MSG0聊天文件弄到本地解密还是直接在目标机上解密

### ISSUE THREAD

**Issue by 1278917999** [AdminTest0/SharpWxDump#49]
在本地解密自己聊天记录显示成功  也能在Navicat 打开

**Comment by 1278917999** [comment]
> 在本地解密自己聊天记录显示成功 也能在Navicat 打开
在目标机上获取 密匙成功  ，然后把msg0文件考回来，解密不成功  
![image](https://github.com/AdminTest0/SharpWxDump/assets/140152084/3d032251-a20c-439c-b022-3fa31ff5936b)
怎么解

**Comment by AdminTest0** [comment]
少了-d参数
-k 密钥 -d 文件

**Comment by 1278917999** [comment]
> 少了-d参数 -k 密钥 -d 文件

加上后 还是不行    是不是因为我解密的是别的电脑上弄过来的   两个电脑数据库不匹配呢   
![image](https://github.com/AdminTest0/SharpWxDump/assets/140152084/3e4dc77b-5f63-4046-941a-a6d48a30e258)

**Comment by 1278917999** [comment]
> 少了-d参数 -k键-d文件

可以不可以解决一下

**Comment by 1278917999** [comment]
![image](https://github.com/AdminTest0/SharpWxDump/assets/140152084/70e2f9e2-44b1-47e2-8623-5b12f36d71c5)

**Comment by 1278917999** [comment]
![image](https://github.com/AdminTest0/SharpWxDump/assets/140152084/3304229d-a4ee-435d-9ba4-79752af5185c)
这种问题怎么解决啊
