### ISSUE TITLE
3.7.6.44微信版本不支持

### ISSUE THREAD

**Issue by WhiExplosions** [AdminTest0/SharpWxDump#7]
最新版不能用了，请问下偏移量能跟新下不

**Comment by AdminTest0** [comment]
已更新

**Comment by WhiExplosions** [comment]
牛逼，建议再加一个输出wxid的。或者WeChat Files下的具体路径。
因为同一个pc可能登录过多个wx账号，而内存中抓出来的key只能解密其中一个。
